### ISSUE TITLE
set up bunbun repo as test

### ISSUE THREAD

**Issue by meozhang** [meozhang/bunbun#1]
set up bunbun repo as test
**description**

```[tasklist]
### Tasks
- [ ] setup vs code
- [ ] try out PR
```

```[tasklist]
### Tasks
- [ ] try out another task list
```

**Comment by meozhang** [comment]
comment 1
comment 1
@meozhang

**Comment by meozhang** [comment]
comment 2
